domain:
  world:
    xmin: 0.0
    xmax: 30.0
    ymin: 0.0
    ymax: 30.0
  rovers: 2
  pois: 1
  coupling: 2

scenario:
  nSteps: 1
  nEps: 1
  staticOrRandom: 1
  evalFunc: G

learning:
  ccea:
    nPop: 15
  network:
    nInputs: 8
    nHidden: 16
    nOutputs: 2