domain:
  world:
    xmin: 0.0
    xmax: 30.0
    ymin: 0.0
    ymax: 30.0
  rovers: 2
  pois: 2
  coupling: 2

domain_agent:
  rovers: 3
  pois: 0
  coupling: 3

domain_poi:
  rovers: 1
  pois: 2
  coupling: 1

scenario:
  nSteps: 30
  nEps: 1
  staticOrRandom: 1
  evalFunc: G

learning:
  ccea:
    nPop: 15
  network:
    nInputs: 8
    nHidden: 16
    nOutputs: 2