# A list of all experiments to run
# All entries in this list must be a top level node in 
experiments:
  #- exptarget
  - onepoi
  #- farpoi
  #- teamforming2
  #- teamforming3
  #- teams2
  #- teams3
  #- teams4


# Explanation of variables for a single experiment
# train : 1 - will train the neural nets regardless of if pre-trained nets are present.
#         0 - will only train neural nets if pre-trained nets are not present
# netfile: string - location neural nets will be stored and read from. Nets are
#                      stored regardless of reading policy.
# biasStart: 1 - Agents will start in center noc-tant. POIs are not in center noc-tant.
#            0 - Agents are randomly placed in all of grid
control:
  train: false
  netfile: control.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 25.0
    ymax: 25.0
  ccea_pop: 15
  nRovs: 18
  nPOIs: 6
  coupling: 1
  nEps: 1000
  nSteps: 30
  biasStart: 0
  staticOrRandom: 1
  type: R
  output: 0
  ind:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  objective:
    type: G
    coupling: 3
    obsR: 4

exptarget:
  train: false
  netfile: expnets.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 20.0
    ymax: 20.0
  ccea_pop: 15
  nRovs: 1
  nPOIs: 4
  coupling: 1
  nEps: 1000
  nSteps: 40
  biasStart: 1
  staticOrRandom: 1
  type: P
  output: 1
  ind:
    - 4
    - 5
    - 6
    - 7
  objective:
    type: Exp
    coupling: 4
    obsR: 4
    
teamforming2:
  train: false
  netfile: teamforming2.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 40.0
    ymax: 40.0
  ccea_pop: 15
  nRovs: 2
  nPOIs: 0
  coupling: 1
  nEps: 1000
  nSteps: 20
  biasStart: 0
  staticOrRandom: 1
  type: A
  ind:
    - 0
    - 1
    - 2
    - 3
  output: 0
  objective:
    type: T
    coupling: 1
    obsR: 4

teamforming3:
  train: false
  netfile: teamforming3.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 40.0
    ymax: 40.0
  ccea_pop: 15
  nRovs: 3
  nPOIs: 0
  coupling: 1
  nEps: 1000
  nSteps: 30
  biasStart: 0
  staticOrRandom: 1
  type: A
  ind:
    - 0
    - 1
    - 2
    - 3
  output: 0
  objective:
    type: T
    coupling: 2
    obsR: 4

teamforming4:
  train: false
  netfile: teamforming4.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 40.0
    ymax: 40.0
  ccea_pop: 15
  nRovs: 4
  nPOIs: 0
  coupling: 1
  nEps: 200
  nSteps: 35
  biasStart: 0
  staticOrRandom: 1
  type: A
  ind:
    - 0
    - 1
    - 2
    - 3
  output: 0
  objective:
    type: T
    coupling: 3
    obsR: 4

teams2:
  train: false
  netfile: teams2.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 40.0
    ymax: 40.0
  ccea_pop: 15
  nRovs: 6
  nPOIs: 0
  coupling: 1
  nEps: 1000
  nSteps: 20
  biasStart: 0
  staticOrRandom: 1
  type: A
  ind:
    - 0
    - 1
    - 2
    - 3
  output: 0
  objective:
    type: UT
    coupling: 2
    obsR: 2

teams3:
  train: false
  netfile: teams3.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 40.0
    ymax: 40.0
  ccea_pop: 15
  nRovs: 9
  nPOIs: 0
  coupling: 1
  nEps: 1000
  nSteps: 25
  biasStart: 0
  staticOrRandom: 1
  type: A
  ind:
    - 0
    - 1
    - 2
    - 3
  output: 0
  objective:
    type: UT
    coupling: 3
    obsR: 3

teams4:
  train: false
  netfile: teams4.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 40.0
    ymax: 40.0
  ccea_pop: 15
  nRovs: 12
  nPOIs: 0
  coupling: 1
  nEps: 1000
  nSteps: 30
  biasStart: 0
  staticOrRandom: 1
  type: A
  ind:
    - 0
    - 1
    - 2
    - 3
  output: 0
  objective:
    type: UT
    coupling: 4
    obsR: 4


NeuralRover:
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 30.0
    ymax: 30.0
  ccea_pop: 15
  nRovs: 4
  nPOIs: 4
  coupling: 6
  nEps: 200
  nSteps: 20
  biasStart: 0
  staticOrRandom: 1
  type: R
  output: 1
  input: 0
    
onepoi:
  train: false
  netfile: onepoi.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 30.0
    ymax: 30.0
  ccea_pop: 15
  nRovs: 1
  nPOIs: 2
  coupling: 1
  nEps: 1000
  nSteps: 25
  biasStart: 1
  staticOrRandom: 1
  type: P
  output: 0
  ind:
    - 4
    - 5
    - 6
    - 7
  objective:
    type: G
    coupling: 1
    obsR: 4

farpoi:
  train: false
  netfile: farpoi.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 40.0
    ymax: 40.0
  ccea_pop: 15
  nRovs: 1
  nPOIs: 3
  coupling: 1
  nEps: 1000
  nSteps: 25
  biasStart: 0
  staticOrRandom: 1
  type: P
  output: 0
  ind:
    - 4
    - 5
    - 6
    - 7
  objective:
    type: G
    coupling: 1
    obsR: 20

coupled:
  train: true
  netfile: coupled.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 20.0
    ymax: 20.0
  ccea_pop: 15
  nRovs: 2
  nPOIs: 2
  coupling: 1
  nEps: 1000
  nSteps: 25
  biasStart: 1
  staticOrRandom: 1
  type: R
  output: 0
  ind:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  objective:
    type: D
    coupling: 2
    obsR: 6

coupledNoBias:
  train: true
  netfile: coupledNoBias.nets
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 20.0
    ymax: 20.0
  ccea_pop: 15
  nRovs: 2
  nPOIs: 2
  coupling: 1
  nEps: 1000
  nSteps: 30
  biasStart: 0
  staticOrRandom: 1
  type: R
  output: 0
  ind:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  objective:
    type: D
    coupling: 2
    obsR: 6

# Coupling for POI only is fixed at 1

exploretwo:
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 30.0
    ymax: 30.0
  ccea_pop: 15
  nRovs: 6
  nPOIs: 0
  coupling: 2
  nEps: 1
  nSteps: 1
  biasStart: 0
  staticOrRandom: 1
  type: E
  output: 1
  ind:
    - 0
    - 1
    - 2
    - 3

exploreone:
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 30.0
    ymax: 30.0
  ccea_pop: 15
  nRovs: 6
  nPOIs: 0
  coupling: 1
  nEps: 100
  nSteps: 20
  biasStart: 0
  staticOrRandom: 1
  type: E
  output: 1
  ind:
    - 0
    - 1
    - 2
    - 3
    
