domain:
  world:
    xmin: 0.0
    xmax: 30.0
    ymin: 0.0
    ymax: 30.0
  rovers: 9
  pois: 4
  coupling: 6

domain_agent:
  rovers: 3
  pois: 0
  coupling: 3

domain_poi:
  rovers: 2
  pois: 3
  coupling: 1

scenario:
  nSteps: 30
  nEps: 500
  staticOrRandom: 1
  evalFunc: G
  poi:
    nEps: 2000
  agent:
    nEps: 200

learning:
  ccea:
    nPop: 20
  network:
    nInputs: 8
    nHidden: 16
    nOutputs: 2