# A list of all experiments to run
# All entries in this list must be a top level node in 
experiments:
  - twoagent

twoagent:
  world:
    xmin: 0.0
    ymin: 0.0
    xmax: 30.0
    ymax: 30.0
  ccea_pop: 15
  nRovs: 4
  nPOIs: 0
  coupling: 2
  nEps: 500
  nSteps: 20
  biasStart: 0
  staticOrRandom: 1
  type: A
  ind:
    - 0
    - 1
    - 2
    - 3
  output: 1
  
